# docker-compose.yml
version: '3.1'
services:
  db:
    image: postgres
    ports:
      - "5432:5432/tcp"
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
       - ./data:/var/lib/postgresql/data